### ISSUE TITLE
setHStretch / setVStretch

### ISSUE THREAD

**Issue by MrTomRod** [AABoyles/TidyTree#28]
Hi!

I want to shrink the dendrogram slightly because the labels are cut:

![image](https://user-images.githubusercontent.com/40867365/80804111-7619d500-8bb4-11ea-9b06-d1693236ecdc.png)

From the documentation, I figured I could use `setHStretch`, just like I can use `setType` and other functions.

```javascript
tree = new TidyTree(newick ? newick : tree.data.clone(), { ... })
tree = tree.setHStretch(0.5)
```

But I get this error: `TypeError: tree.setHStretch is not a function`.
What am I doing wrong?

**Comment by AABoyles** [comment]
Hey @MrTomRod! Where are you getting your copy of TidyTree from? I notice that the README references a CDN with an old version from before we implemented setHStretch, which would make some sense. I'll definitely update that, but in the meanwhile, try loading the script like so:

```html
<script src="https://unpkg.com/tidytree@0.5.0/dist/tidytree.min.js"></script>
```

And let us know if that helps or not. Thank you!

**Comment by MrTomRod** [comment]
That was indeed the problem! I was on version 0.3.x. However, now, I get this error even on this trivial hello-world script!

`TypeError: can't convert undefined to object tidytree.min.js:1:437`

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8">

	<script src="https://d3js.org/d3.v5.min.js"></script>
	<script src="https://unpkg.com/tidytree@0.5.0/dist/tidytree.min.js"></script>
</head>

<body></body>

<script type="text/javascript">
	let newick = "(A:0.1,B:0.2,(C:0.3,D:0.4):0.5);";
	let tree = new TidyTree(newick, { parent: "body" });
</script>
````

**Comment by AABoyles** [comment]
Oh, yikes! Thanks, I'll straighten this out and get back to you.

**Comment by MrTomRod** [comment]
i'm just glad it wasn't my fault. :)

**Comment by AABoyles** [comment]
Nope, 100% mine. I messed up the event handler. Fixed and re-released. Try using https://unpkg.com/tidytree@0.5.1/dist/tidytree.min.js

**Comment by MrTomRod** [comment]
It's working again! Thanks.
